apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: observability
spec:
  type: LoadBalancer
  selector:
    app: jaeger
  ports:
    - name: http
      port: 16686
      targetPort: 16686
    - name: thrift
      port: 6831
      targetPort: 6831
    - name: thrift-udp
      port: 6832
      targetPort: 6832



