apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686
              name: http
            - containerPort: 6831
              name: thrift
            - containerPort: 6832
              name: thrift-udp
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"

